#すでに同じIPから 設定した人数サーバーに参加していて
#サーバーに参加できなかった時に表示されるメッセージ
KickText: |-
  すでに同じIPからプレイヤーがログインしているため
  %sは参加できません
  現在サーバーには同じIPから最大%d人まで参加できます

#同じIPからは何人までサーバーに参加できるようにするか 2人までにするには2
max: 2

#すでに同じIPから 設定した人数サーバーに参加しても
#その設定を無視してサーバーに参加できるプレイヤーのUUID
#「-」は書いても書かなくてもいい
ExceptionUUID:
  - "test-test-test"
  - "testtesttest"